/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/readiness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_api_v1_readiness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/benchmark-workflows": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Benchmark Workflows */
    get: operations["benchmark_workflows_api_v1_benchmark_workflows_get"];
    put?: never;
    /** Create Benchmark Workflow */
    post: operations["create_benchmark_workflow_api_v1_benchmark_workflows_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/benchmark-workflows/{workflow_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Benchmark Workflow */
    get: operations["benchmark_workflow_api_v1_benchmark_workflows__workflow_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/benchmark-workflows/{workflow_id}/advance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Advance Benchmark Workflow */
    post: operations["advance_benchmark_workflow_api_v1_benchmark_workflows__workflow_id__advance_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/benchmark-workflows/{workflow_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel Benchmark Workflow */
    post: operations["cancel_benchmark_workflow_api_v1_benchmark_workflows__workflow_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/benchmark-workflows/{workflow_id}/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Benchmark Workflow Report */
    get: operations["benchmark_workflow_report_api_v1_benchmark_workflows__workflow_id__report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/datasets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Datasets */
    get: operations["datasets_api_v1_datasets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/datasets/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload */
    post: operations["upload_api_v1_datasets_validate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/datasets/{dataset_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dataset */
    get: operations["dataset_api_v1_datasets__dataset_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/datasets/{dataset_id}/review-packet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Packet */
    get: operations["packet_api_v1_datasets__dataset_id__review_packet_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/datasets/{dataset_id}/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reviews */
    post: operations["reviews_api_v1_datasets__dataset_id__reviews_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/estimate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Estimate */
    post: operations["estimate_api_v1_runs_estimate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs */
    get: operations["runs_api_v1_runs_get"];
    put?: never;
    /** Start Run */
    post: operations["start_run_api_v1_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run */
    get: operations["run_api_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_v1_runs__run_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/rescore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rescore */
    post: operations["rescore_api_v1_runs__run_id__rescore_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Summary */
    get: operations["summary_api_v1_runs__run_id__summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/cases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cases */
    get: operations["cases_api_v1_runs__run_id__cases_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/playback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Playback */
    get: operations["playback_api_v1_runs__run_id__playback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/cases/{case_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Case Detail */
    get: operations["case_detail_api_v1_runs__run_id__cases__case_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/charts/{chart_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chart */
    get: operations["chart_api_v1_runs__run_id__charts__chart_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/comparison/{other_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compare Runs */
    get: operations["compare_runs_api_v1_runs__run_id__comparison__other_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/exports/{format}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export */
    get: operations["export_api_v1_runs__run_id__exports__format__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_v1_runs__run_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/calibrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Calibrations */
    get: operations["calibrations_api_v1_calibrations_get"];
    put?: never;
    /** Calibrate */
    post: operations["calibrate_api_v1_calibrations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/calibrations/{calibration_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Calibration */
    get: operations["calibration_api_v1_calibrations__calibration_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/protocols": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Protocols */
    get: operations["protocols_api_v1_protocols_get"];
    put?: never;
    /** Freeze */
    post: operations["freeze_api_v1_protocols_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/protocols/{protocol_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Protocol */
    get: operations["protocol_api_v1_protocols__protocol_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BenchmarkAdvanceRequest */
    BenchmarkAdvanceRequest: {
      /**
       * Confirm Live Calls
       * @default false
       */
      confirm_live_calls: boolean;
      /**
       * Confirm Remote Data
       * @default false
       */
      confirm_remote_data: boolean;
    };
    /** BenchmarkWorkflowRequest */
    BenchmarkWorkflowRequest: {
      /** Name */
      name: string;
      /** Dataset Jsonl */
      dataset_jsonl: string;
      /**
       * Profile
       * @default standard
       * @enum {string}
       */
      profile: "standard" | "full";
      /**
       * Publication
       * @default false
       */
      publication: boolean;
    };
    /** Body_upload_api_v1_datasets_validate_post */
    Body_upload_api_v1_datasets_validate_post: {
      /** File */
      file: string;
    };
    /** CalibrationRequest */
    CalibrationRequest: {
      /** Run Id */
      run_id: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** JevConfiguration */
    JevConfiguration: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Model
       * @default jev-1.13.0
       */
      model: string;
      /**
       * Timeout Seconds
       * @default 30
       */
      timeout_seconds: number;
      /**
       * Max Retries
       * @default 2
       */
      max_retries: number;
    };
    /** LayaConfiguration */
    LayaConfiguration: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /**
       * Mode
       * @default router
       * @constant
       */
      mode: "router";
      /**
       * Device
       * @default auto
       * @enum {string}
       */
      device: "auto" | "cpu" | "mps" | "cuda";
      /**
       * Preload
       * @default true
       * @constant
       */
      preload: true;
      /**
       * Timeout Seconds
       * @default 120
       */
      timeout_seconds: number;
      /** Checkpoint Revision */
      checkpoint_revision?: string | null;
      /**
       * Checkpoint
       * @default router
       * @enum {string}
       */
      checkpoint: "router" | "english" | "multilingual" | "typed-decisions";
    };
    /** MetricConfiguration */
    MetricConfiguration: {
      /**
       * Ece Bins
       * @default 10
       */
      ece_bins: number;
      /** Confidence Thresholds */
      confidence_thresholds?: number[];
      /**
       * Bootstrap Samples
       * @default 2000
       */
      bootstrap_samples: number;
      /**
       * Bootstrap Seed
       * @default 20260924
       */
      bootstrap_seed: number;
      /** Local Hourly Cost Usd */
      local_hourly_cost_usd?: number | null;
      /** Local Cost Basis */
      local_cost_basis?: string | null;
      /**
       * Jev Usd Per Million Input Tokens
       * @default 0.042
       */
      jev_usd_per_million_input_tokens: number;
    };
    /** Performance */
    Performance: {
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
      /** Concurrency */
      concurrency?: number[];
      /** Batch Sizes */
      batch_sizes?: number[];
      /**
       * Sample Size
       * @default 30
       */
      sample_size: number;
    };
    /** PlaybackCase */
    PlaybackCase: {
      /** Id */
      id: string;
      /**
       * Primitive
       * @enum {string}
       */
      primitive: "choice" | "noul" | "score";
      /** Variant */
      variant: string;
      /** Instructions */
      instructions: string;
      /** Input Preview */
      input_preview: string;
      /** Options */
      options: components["schemas"]["PlaybackOption"][];
      /** Expected Key */
      expected_key: string;
    };
    /** PlaybackFrame */
    PlaybackFrame: {
      /** Key */
      key: string;
      /** Ordinal */
      ordinal: number;
      /** Sealed */
      sealed: boolean;
      /** Suite */
      suite: string;
      /** Repetition */
      repetition: number;
      /** Concurrency */
      concurrency: number;
      /** Batch Size */
      batch_size: number;
      case: components["schemas"]["PlaybackCase"] | null;
      /** Systems */
      systems: {
        [key: string]: components["schemas"]["PlaybackOutcome"];
      };
    };
    /** PlaybackOption */
    PlaybackOption: {
      /** Id */
      id: string;
      /** Label */
      label: string;
    };
    /** PlaybackOutcome */
    PlaybackOutcome: {
      /** Evaluation Id */
      evaluation_id: string;
      /**
       * State
       * @enum {string}
       */
      state: "pending" | "success" | "failed" | "not_completed";
      /** Selected */
      selected?: string | null;
      /** Probabilities */
      probabilities?: {
        [key: string]: number;
      };
      /** Correctness */
      correctness?: boolean | null;
      /** Latency Ms */
      latency_ms?: number | null;
      /**
       * Retry Count
       * @default 0
       */
      retry_count: number;
      /** Error */
      error?: string | null;
    };
    /** PlaybackPage */
    PlaybackPage: {
      /** Items */
      items: components["schemas"]["PlaybackFrame"][];
      /** Next Cursor */
      next_cursor: number | null;
      /** Total Frames */
      total_frames: number;
      /** Withheld Frames */
      withheld_frames: number;
      /** Latest Available */
      latest_available: number | null;
      /** Run Status */
      run_status: string;
    };
    /** ProtocolRequest */
    ProtocolRequest: {
      /** Dataset Id */
      dataset_id: string;
      /** Configurations */
      configurations: {
        [key: string]: components["schemas"]["RunConfiguration"];
      };
    };
    /** Repeatability */
    Repeatability: {
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
      /**
       * Repetitions
       * @default 5
       */
      repetitions: number;
      /**
       * Sample Size
       * @default 30
       */
      sample_size: number;
    };
    /** RescoreRequest */
    RescoreRequest: {
      /**
       * Scoring Version
       * @default 1.0.0
       */
      scoring_version: string;
    };
    /** ReviewRequest */
    ReviewRequest: {
      /** Reviews */
      reviews: {
        [key: string]: unknown;
      }[];
    };
    /** RunConfiguration */
    RunConfiguration: {
      /**
       * Name
       * @default Paired evaluation
       */
      name: string;
      /**
       * Track
       * @default default
       * @enum {string}
       */
      track: "default" | "production-tuned";
      /** Dataset Ref */
      dataset_ref: string;
      /** Dataset Digest */
      dataset_digest?: string | null;
      /**
       * Seed
       * @default 20260924
       */
      seed: number;
      /**
       * Mode
       * @default live
       * @enum {string}
       */
      mode: "live" | "fake";
      systems?: components["schemas"]["Systems"];
      suites?: components["schemas"]["Suites"];
      metrics?: components["schemas"]["MetricConfiguration"];
      /** Calibration Id */
      calibration_id?: string | null;
      /** Protocol Id */
      protocol_id?: string | null;
      /**
       * Publication
       * @default false
       */
      publication: boolean;
      /**
       * Acknowledge Remote
       * @default false
       */
      acknowledge_remote: boolean;
      /** Instruction Overrides */
      instruction_overrides?: {
        [key: string]: string;
      };
    };
    /** Suites */
    Suites: {
      /**
       * Quality
       * @default true
       * @constant
       */
      quality: true;
      /**
       * Calibration
       * @default true
       * @constant
       */
      calibration: true;
      /**
       * Robustness
       * @default true
       * @constant
       */
      robustness: true;
      repeatability?: components["schemas"]["Repeatability"];
      performance?: components["schemas"]["Performance"];
      /**
       * Context Length
       * @default false
       */
      context_length: boolean;
      /**
       * Option Cardinality
       * @default false
       */
      option_cardinality: boolean;
    };
    /** Systems */
    Systems: {
      jev?: components["schemas"]["JevConfiguration"];
      laya?: components["schemas"]["LayaConfiguration"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  readiness_api_v1_readiness_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  benchmark_workflows_api_v1_benchmark_workflows_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  create_benchmark_workflow_api_v1_benchmark_workflows_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BenchmarkWorkflowRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  benchmark_workflow_api_v1_benchmark_workflows__workflow_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workflow_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  advance_benchmark_workflow_api_v1_benchmark_workflows__workflow_id__advance_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workflow_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BenchmarkAdvanceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_benchmark_workflow_api_v1_benchmark_workflows__workflow_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workflow_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  benchmark_workflow_report_api_v1_benchmark_workflows__workflow_id__report_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workflow_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  datasets_api_v1_datasets_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  upload_api_v1_datasets_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_api_v1_datasets_validate_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dataset_api_v1_datasets__dataset_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  packet_api_v1_datasets__dataset_id__review_packet_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reviews_api_v1_datasets__dataset_id__reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  estimate_api_v1_runs_estimate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunConfiguration"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  runs_api_v1_runs_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        status?: string | null;
        track?: string | null;
        dataset?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_run_api_v1_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunConfiguration"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_api_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_api_v1_runs__run_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rescore_api_v1_runs__run_id__rescore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RescoreRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  summary_api_v1_runs__run_id__summary_get: {
    parameters: {
      query?: {
        domain?: string | null;
        primitive?: string | null;
        variant?: string | null;
        split?: string | null;
        disagreement?: boolean | null;
        jev_correct?: boolean | null;
        laya_correct?: boolean | null;
        confidence_min?: number;
        confidence_max?: number;
        error_category?: string | null;
        q?: string;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cases_api_v1_runs__run_id__cases_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        domain?: string | null;
        primitive?: string | null;
        variant?: string | null;
        split?: string | null;
        disagreement?: boolean | null;
        jev_correct?: boolean | null;
        laya_correct?: boolean | null;
        confidence_min?: number;
        confidence_max?: number;
        error_category?: string | null;
        q?: string;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  playback_api_v1_runs__run_id__playback_get: {
    parameters: {
      query?: {
        after?: number;
        limit?: number;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlaybackPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  case_detail_api_v1_runs__run_id__cases__case_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chart_api_v1_runs__run_id__charts__chart_id__get: {
    parameters: {
      query?: {
        domain?: string | null;
        primitive?: string | null;
        variant?: string | null;
        split?: string | null;
        disagreement?: boolean | null;
        jev_correct?: boolean | null;
        laya_correct?: boolean | null;
        confidence_min?: number;
        confidence_max?: number;
        error_category?: string | null;
        q?: string;
      };
      header?: never;
      path: {
        run_id: string;
        chart_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  compare_runs_api_v1_runs__run_id__comparison__other_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        other_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_api_v1_runs__run_id__exports__format__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
        format: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_api_v1_runs__run_id__events_get: {
    parameters: {
      query?: {
        after?: number;
      };
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  calibrations_api_v1_calibrations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  calibrate_api_v1_calibrations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalibrationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  calibration_api_v1_calibrations__calibration_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        calibration_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  protocols_api_v1_protocols_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  freeze_api_v1_protocols_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProtocolRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  protocol_api_v1_protocols__protocol_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        protocol_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
